// <auto-generated />
using System;
using EWS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EWS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319090046_FixEnumToInt")]
    partial class FixEnumToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EWS.Domain.Entities.Delegation", b =>
                {
                    b.Property<int>("DelegationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DelegationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromPositionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DelegationId");

                    b.HasIndex("ToPositionId");

                    b.HasIndex("FromPositionId", "IsActive", "StartDate", "EndDate")
                        .HasDatabaseName("IX_Delegation_Active");

                    b.ToTable("Delegations", "dbo");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeptNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DeptCode")
                        .IsUnique();

                    b.HasIndex("DivisionId");

                    b.ToTable("Departments", "dbo");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DivisionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DivisionNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DivisionId");

                    b.HasIndex("DivisionCode")
                        .IsUnique();

                    b.ToTable("Divisions", "dbo");
                });

            modelBuilder.Entity("EWS.Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DocCode")
                        .HasColumnType("int");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DocumentTypeId");

                    b.HasIndex("DocCode")
                        .IsUnique();

                    b.ToTable("DocumentTypes", "wf");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees", "dbo");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsChiefLevel")
                        .HasColumnType("bit");

                    b.Property<int>("JobGrade")
                        .HasColumnType("int");

                    b.Property<int?>("ParentPositionId")
                        .HasColumnType("int");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PositionShortName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SecretaryPositionId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WfScopeType")
                        .HasColumnType("int");

                    b.HasKey("PositionId");

                    b.HasIndex("ParentPositionId");

                    b.HasIndex("PositionCode")
                        .IsUnique();

                    b.HasIndex("SecretaryPositionId");

                    b.HasIndex("SectionId");

                    b.ToTable("Positions", "dbo");
                });

            modelBuilder.Entity("EWS.Domain.Entities.PositionAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVacant")
                        .HasColumnType("bit");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PositionId", "IsActive", "StartDate", "EndDate")
                        .HasDatabaseName("IX_PositionAssignment_Active");

                    b.ToTable("PositionAssignments", "dbo");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SectNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SectionId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SectCode")
                        .IsUnique();

                    b.ToTable("Sections", "dbo");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<DateTime?>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActorActingAsPositionId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActorEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssignedPositionId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EscalatedFromPositionId")
                        .HasColumnType("int");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ActorActingAsPositionId");

                    b.HasIndex("ActorEmployeeId");

                    b.HasIndex("AssignedPositionId");

                    b.HasIndex("StepId");

                    b.HasIndex("InstanceId", "StepOrder")
                        .HasDatabaseName("IX_WorkflowApproval_InstanceStep");

                    b.ToTable("WorkflowApprovals", "wf");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryId"));

                    b.Property<Guid?>("ActorEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActorPositionId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DataSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("ActorEmployeeId");

                    b.HasIndex("ActorPositionId");

                    b.HasIndex("InstanceId", "OccurredAt")
                        .HasDatabaseName("IX_WorkflowHistory_Instance");

                    b.ToTable("WorkflowHistories", "wf");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActingAsPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBySecretaryPositionId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalDocRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSpecialItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<int?>("PreApprovalChiefPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PreApprovalConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmitterEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubmitterPositionId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstanceId");

                    b.HasIndex("ActingAsPositionId");

                    b.HasIndex("CreatedBySecretaryPositionId");

                    b.HasIndex("DocumentNo")
                        .IsUnique();

                    b.HasIndex("PreApprovalChiefPositionId");

                    b.HasIndex("SubmitterEmployeeId");

                    b.HasIndex("SubmitterPositionId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("IX_WorkflowInstance_Status");

                    b.ToTable("WorkflowInstances", "wf");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<int>("ApproverType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EscalationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("SpecificPositionCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StepId");

                    b.HasIndex("TemplateId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowStep_TemplateOrder");

                    b.ToTable("WorkflowSteps", "wf");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("Condition1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condition2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condition3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condition4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condition5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FlowCode")
                        .HasColumnType("int");

                    b.Property<string>("FlowDesc")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasSpecialItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WfScopeType")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.HasIndex("DocumentTypeId", "FlowCode")
                        .IsUnique();

                    b.ToTable("WorkflowTemplates", "wf");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Delegation", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Position", "FromPosition")
                        .WithMany("DelegationsFrom")
                        .HasForeignKey("FromPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWS.Domain.Entities.Position", "ToPosition")
                        .WithMany("DelegationsTo")
                        .HasForeignKey("ToPositionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromPosition");

                    b.Navigation("ToPosition");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Department", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Division", "Division")
                        .WithMany("Departments")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Position", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Position", "ParentPosition")
                        .WithMany("SubordinatePositions")
                        .HasForeignKey("ParentPositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Position", "SecretaryPosition")
                        .WithMany()
                        .HasForeignKey("SecretaryPositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Section", "Section")
                        .WithMany("Positions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentPosition");

                    b.Navigation("SecretaryPosition");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EWS.Domain.Entities.PositionAssignment", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Employee", "Employee")
                        .WithMany("PositionAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWS.Domain.Entities.Position", "Position")
                        .WithMany("Assignments")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Section", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowApproval", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Position", "ActorActingAsPosition")
                        .WithMany()
                        .HasForeignKey("ActorActingAsPositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Employee", "ActorEmployee")
                        .WithMany()
                        .HasForeignKey("ActorEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Position", "AssignedPosition")
                        .WithMany()
                        .HasForeignKey("AssignedPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWS.Domain.Entities.WorkflowInstance", "Instance")
                        .WithMany("Approvals")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWS.Domain.Entities.WorkflowStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorActingAsPosition");

                    b.Navigation("ActorEmployee");

                    b.Navigation("AssignedPosition");

                    b.Navigation("Instance");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowHistory", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Employee", "ActorEmployee")
                        .WithMany()
                        .HasForeignKey("ActorEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Position", "ActorPosition")
                        .WithMany()
                        .HasForeignKey("ActorPositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.WorkflowInstance", "Instance")
                        .WithMany("Histories")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorEmployee");

                    b.Navigation("ActorPosition");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowInstance", b =>
                {
                    b.HasOne("EWS.Domain.Entities.Position", "ActingAsPosition")
                        .WithMany()
                        .HasForeignKey("ActingAsPositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Position", "CreatedBySecretaryPosition")
                        .WithMany()
                        .HasForeignKey("CreatedBySecretaryPositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Position", "PreApprovalChiefPosition")
                        .WithMany()
                        .HasForeignKey("PreApprovalChiefPositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EWS.Domain.Entities.Employee", "SubmitterEmployee")
                        .WithMany()
                        .HasForeignKey("SubmitterEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWS.Domain.Entities.Position", "SubmitterPosition")
                        .WithMany()
                        .HasForeignKey("SubmitterPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWS.Domain.Entities.WorkflowTemplate", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActingAsPosition");

                    b.Navigation("CreatedBySecretaryPosition");

                    b.Navigation("PreApprovalChiefPosition");

                    b.Navigation("SubmitterEmployee");

                    b.Navigation("SubmitterPosition");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("EWS.Domain.Entities.WorkflowTemplate", "Template")
                        .WithMany("Steps")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.HasOne("EWS.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany("Templates")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Department", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Division", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("EWS.Domain.Entities.DocumentType", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Employee", b =>
                {
                    b.Navigation("PositionAssignments");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Position", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("DelegationsFrom");

                    b.Navigation("DelegationsTo");

                    b.Navigation("SubordinatePositions");
                });

            modelBuilder.Entity("EWS.Domain.Entities.Section", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("EWS.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
